import Image from "next/image";
import addImage from "@/images/icons/add-image.svg";
import facebookSvg from "@/images/icons/Facebook.svg";
import googleSvg from "@/images/icons/Google.svg";
import helpSvg from "@/images/icons/help.svg";
import homeSvg from "@/images/icons/home.svg";
import logoutSvg from "@/images/icons/logout.svg";
import messageSvg from "@/images/icons/message.svg";
import myAccountSvg from "@/images/icons/my-account.svg";
import twitterSvg from "@/images/icons/Twitter.svg";
import wishlistSvg from "@/images/icons/wishlist.svg";
import type { LucideIcon } from "lucide-react";
import {
  AlarmClock,
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  BarChart3,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  Copy,
  CreditCard,
  Crop,
  DollarSign,
  Download,
  Edit,
  Eye,
  EyeOff,
  FileTerminal,
  Filter,
  Footprints,
  HardHat,
  Image as ImageIcon,
  Laptop,
  Loader2,
  LogOut,
  MapPinned,
  Menu,
  MessageSquare,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Package,
  Plus,
  PlusCircle,
  RefreshCw,
  Search,
  Send,
  Settings,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  SlidersHorizontal,
  SquareUser,
  Star,
  SunMedium,
  Trash,
  Trophy,
  Twitter,
  UploadCloud,
  User,
  Volume2,
  VolumeX,
  Wallet,
  X,
} from "lucide-react";

export const ImageSvgIcons = {
  FacebookSvg: <Image src={facebookSvg} alt="Facebook" />,
  TwitterSvg: <Image src={twitterSvg} alt="Twitter" />,
  GoogleSvg: <Image src={googleSvg} alt="Google" />,
  MyAccountSvg: <Image src={myAccountSvg} alt="my acount" />,
  LogoutSvg: <Image src={logoutSvg} alt="logout" />,
  MessageSvg: <Image src={messageSvg} alt="messgae" />,
  WishlistSvg: <Image src={wishlistSvg} alt="whishlist" />,
  HelpSvg: <Image src={helpSvg} alt="help" />,
  HomeSvg: <Image src={homeSvg} alt="home" />,
  AddImage: <Image src={addImage} alt="add image" />,
};
export type Icons = LucideIcon;

export const Icons = {
  SunMedium,
  Moon,
  Laptop,
  Star,
  Twitter,
  X,
  Loader2,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronUp,
  ChevronDown,
  Trophy,
  ChevronsUpDown,
  ArrowUp,
  ArrowDown,
  Menu,
  MoreVertical,
  MoreHorizontal,
  Sliders,
  SlidersHorizontal,
  Circle,
  Check,
  Plus,
  PlusCircle,
  Minus,
  Eye,
  MapPinned,
  EyeOff,
  Trash,
  Edit,
  Crop,
  RefreshCw,
  Send,
  Copy,
  Download,
  AlertTriangle,
  Search,
  Filter,
  AlarmClock,
  CalendarDays,
  User,
  FileTerminal,
  Settings,
  LogOut,
  Volume2,
  VolumeX,
  MessageSquare,
  CreditCard,
  Wallet,
  DollarSign,
  ShoppingCart,
  Package,
  ShoppingBag,
  BarChart3,
  UploadCloud,
  ImageIcon,
  Shirt,
  Footprints,
  HardHat,
  SquareUser,
};
